Add an authproto_pam helper that communicates with PAM. (#45)
Add an authproto_pam helper that communicates with PAM.

This is now used by auth_pam_x11 as sole backend. It can be made
setuid/setgid where necessary to authenticate local users (e.g. on
FreeBSD).

Also renames auth_pam_x11 to auth_x11, and moves auth_htpasswd and
auth_pamtester to authprotos that can be used with auth_x11.

Will fix #43.

diff --git a/helpers/authproto_pamtester.in b/helpers/authproto_pamtester.in
--- a/helpers/authproto_pamtester.in
+++ b/helpers/authproto_pamtester.in
@@ -14,8 +14,33 @@
 # See the License for the specific language governing permissions and
 # limitations under the License.
 
-echo "Enter password:" |\
-  display -window "$XSCREENSAVER_WINDOW" TEXT:-
+echo "P 15"
+echo "Enter password:"
+read -r ptype len
+case "$ptype" in
+  p)
+    # Trick: reading len+1 characters get the password and the terminating
+    # newline - just what we need here.
+    if head -c "$((len+1))" |\
+        @path_to_pamtester@ @pam_service_name@ "$USER" authenticate \
+          >/dev/null 2>&1; then
+      echo "i 11"
+      echo "I know you."
+      exit 0
+    else
+      echo "e 17"
+      echo "Invalid password."
+      exit 1
+    fi
+    ;;
+  x)
+    exit 1
+    ;;
+  *)
+    echo >&2 "Unexpected packet type."
+    exit 1
+    ;;
+esac
 
-exec >/dev/null 2>&1
-exec @with_htpasswd@ -v ~/.xsecurelock.pw "$USER"
+# Shouldn't get here.
+exit 42
