Prefix all error messages we control with "xsecurelock:" for easier grepping in ~/.xsession-errors.

diff --git a/helpers/saver_xscreensaver.in b/helpers/saver_xscreensaver.in
--- a/helpers/saver_xscreensaver.in
+++ b/helpers/saver_xscreensaver.in
@@ -92,7 +92,7 @@ while :; do
     $saver
   fi
   sleep 2
-  echo >&2 "Screen saver failed: $saver. Trying another one..."
+  echo >&2 "xsecurelock: Screen saver failed: $saver. Trying another one..."
   selected=$((selected + 1))
   mode=random
 done &
